# environment id of the task
env_id: "dm_control/cheetah-run-v0"

# Algorithm specific arguments
# total timesteps of the experiments
total_timesteps: 1000000
# the replay memory buffer size
buffer_size: 1000000
# the discount factor gamma
gamma: 0.99
# target smoothing coefficient (default: 0.005)
tau: 0.005
# the batch size of sample from the reply memory
batch_size: 256
# timestep to start learning
learning_starts: 50000
# how often to evaluate the policy
evaluation_freq: 10000
# the learning rate of the policy network optimizer
policy_lr: 0.0003
# the learning rate of the Q network network optimizer
q_lr: 0.001
# whether to use torch.compile.
compile: true

# wingman required params
# https://github.com/jjshoots/Wingman?tab=readme-ov-file#from-wingman-import-wingman
model:
  save_directory: "weights"
  id: ""
  ckpt: 0
  increment_ckpt: false

logging:
  interval: 10000
  max_skips: 5
  greater_than: 0.0
  filename: ""

wandb:
  enable: false
  save_code: false
  run:
    name: ""
    notes: ""
  project:
    name: "my_new_project"
    entity: "wingman"
